
import React, { useState, useMemo, useEffect, useRef } from 'react';
import { 
  LayoutDashboard, 
  Home, 
  Settings, 
  Calculator, 
  DollarSign, 
  Plus, 
  Trash2,
  Save,
  FileText,
  Users,
  Download,
  Upload,
  RefreshCcw,
  Calendar,
  ChevronRight,
  ChevronDown,
  Info,
  X,
  Edit2,
  Clock,
  Link as LinkIcon,
  Maximize2,
  ArrowUpFromLine,
  Minimize2,
  Zap,
  Plug,
  BoxSelect,
  MoreVertical,
  Map as MapIcon,
  Image as ImageIcon,
  ZoomIn,
  ZoomOut,
  Droplets,
  Hammer,
  PaintBucket,
  Layers,
  Umbrella,
  DoorOpen,
  Grid,
  TrendingDown,
  AlertTriangle,
  PieChart as PieChartIcon,
  Target,
  BarChart4,
  Activity,
  Printer
} from 'lucide-react';
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  Legend, 
  ResponsiveContainer, 
  PieChart, 
  Pie, 
  Cell,
  Treemap,
  ScatterChart,
  Scatter,
  ZAxis,
  AreaChart,
  Area
} from 'recharts';
import { INITIAL_ROOMS, INITIAL_PRICES, INITIAL_FIXED_COSTS } from './constants';
import { Room, UnitPrice, FixedCost, Task, ScheduleOverride } from './types';

// --- Styles Constants ---
const STYLES = {
  input: "w-full bg-slate-50 border border-slate-200 text-slate-700 text-sm rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent block p-2.5 transition-all outline-none hover:bg-white print:hidden",
  inputSmall: "bg-slate-50 border border-slate-200 text-slate-700 text-sm rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent block p-1.5 transition-all outline-none text-center print:border-none print:bg-transparent print:p-0 print:text-right",
  inputCompact: "w-full bg-white border border-slate-200 text-slate-700 text-xs rounded-md focus:ring-2 focus:ring-blue-500 focus:border-blue-500 block px-2 py-1 transition-all outline-none shadow-sm font-medium h-7 print:border-none print:bg-transparent print:p-0 print:h-auto print:text-right print:shadow-none",
  label: "block mb-1 text-xs font-semibold text-slate-500 uppercase tracking-wide",
  labelCompact: "block text-[9px] font-bold text-slate-400 uppercase tracking-wider mb-0.5",
  card: "bg-white rounded-xl shadow-sm hover:shadow-md transition-shadow duration-300 ring-1 ring-slate-900/5 print:shadow-none print:ring-1 print:ring-slate-200",
  tableHeader: "bg-slate-50 text-slate-500 text-xs uppercase font-semibold tracking-wider text-left py-3 px-4 border-b border-slate-100 print:bg-slate-100 print:text-slate-900",
  tableCell: "py-3 px-4 text-sm text-slate-600 border-b border-slate-50 group-hover:bg-slate-50/50 transition-colors print:border-slate-200",
};

// --- Helper Functions ---